### ISSUE TITLE
Add CSV exports for reports

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#100]
This was originally mentioned in #82, and will be done as part of Phase II.  The exports are of the full result set.  @trystant says "I think that converting the json to csv and setting the application type should be sufficient."

**Comment by kfogel** [comment]
To clarify what this is about: basically, any set of results they're displaying in the admin area, they'll want to be able to download as a CSV (without pagination interfering, of course).

So say someone is logged in as admin and is displaying the results for "All Regions", with whatever sort applied they want (say, sort-by-date), and there are 1050 results.  That means there are multiple pages (even if they set 500 results per page, that's still three pages, with the last page having 50 results).  The "Export all results as CSV" button should export all 1050 results.  I guess it makes sense to have the CSV rows sorted in the same order as the displayed results, even though sorting matters less for CSV, since it's more for batch processing.

And if someone has filtered to show just (say) the "Idaho/Montana" region, then "Export to CSV" should export all those results -- that is, just results in the "Idaho/Montana" region, again ignoring pagination.  If the results are also *filtered* by date (as opposed to being just sorted by date), then the CSV result set would include only the results within the specified date range.  Etc, etc.

**Comment by kfogel** [comment]
By the way, if it's basically free to also get JSON export along with CSV export, let's do that.  CSV is necessary, of course, for compatibility with Excel and other, ahem, legacy apps.  But JSON is actually slightly better from a programmer point of view; no reason not to offer both if we can.  We don't have enough UI clutter yet to worry about the UI costs of offering two types of export, and even once we do have more UI controls, that's easily solveable.

**Comment by trystant** [comment]
@kfogel After reviewing things, I believe that it would take between 3 - 4 hours to do the CSV export as needed. This includes links for JSON and CSV for the requests. I think we'd need to have a description of  how the filters affect the CSV/JSON that is returned.

**Comment by kfogel** [comment]
Thanks, @trystant.  Does my description in my [earlier comment](https://github.com/redcross/smoke-alarm-portal/issues/100#issuecomment-133058404), of how the filters affect the exports, leave anything unspecified?  Basically, I'm saying that the result set displayed should always be the result set exported, and that the export should list items in the order they are displayed, without pagination (i.e., pretend that the result set displayed always has all the results on one screen).

**Comment by kfogel** [comment]
Bookkeeping: @trystant says 3-4 hours, calendar completion by ~EOB Monday 24 August.

**Comment by trystant** [comment]
At this point, the remaining functionality to verify is the filtering of the results. I've got the strategy of using jQuery to update the URL based upon the filters used. This is in the filter: function in Backbone. I just need to update the URL and that will be solved. I need to do a mentor session, but will finish up after that.

**Comment by kfogel** [comment]
Filtering is not working as of right now, FWIW (commit 5394167da).  I filtered results as per the example in issue #108 -- that issue is about something unrelated, but I happened to be testing filtering and CSV exports when I ran across that other bug, so it's simpler here to just point to that issue for the exact example of the filtering I did -- and then I did a CSV export.  Even though my *displayed* result set had one name, "Testy Westy", my CSV export had two rows: "Testy Westy" and "Karl Fogel" (which were the only two requests in the database at the time).

**Comment by kfogel** [comment]
I wasn't sure if filtering was expected to work at this point or not, by the way.  @trystant from the phrasing in your comment above ("remaining functionality to verify is the filtering of the results") I inferred that the functionality is *working* but not yet *verified*.  But then when I read the rest of the comment, it sounded like maybe it wasn't actually implemented yet?  Not sure.

**Comment by trystant** [comment]
Filtering was not expected to be working and/or implemented at this point.
I outlined a path towards that point but have not implemented it as of that
point. I have one hour left in the max of that estimate and intend to
deliver the filtered link in that timeframe.

On Mon, Aug 24, 2015 at 10:53 PM, Karl Fogel <notifications@github.com>
wrote:

> I wasn't sure if filtering was expected to work at this point or not, by
> the way. @trystant <https://github.com/trystant> from the phrasing in
> your comment above ("remaining functionality to verify is the filtering of
> the results") I inferred that the functionality is *working* but not yet
> *verified*. But then when I read the rest of the comment, it sounded like
> maybe it wasn't actually implemented yet? Not sure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/redcross/smoke-alarm-portal/issues/100#issuecomment-134458550>
> .
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant

**Comment by kfogel** [comment]
*nod*  Sounds good.

When you write a phrase like "the remaining functionality to verify is the filtering of the results", I take it as written: that you're now in verification, which is a post-implementation step.  I didn't waste any time or anything -- would have had to set up the test later in any case, so now it's ready to go for me, which is great.  I'm just explaining why I got confused.  "...to implement" or "to do" or "to write" would say directly what you were trying to say!

(I'm off to bed, but look forward to seeing it in the morning.)

**Comment by trystant** [comment]
So, I ran into challenges with filtering the results. In addition to the commit message on the `100_filter_wip` branch, I wanted to record the seemingly random error I received while working on this path. It occurred when clicking on the "Export CSV" link in the Requests admin. This is a record for posterity.

So, all in all, the general export functionality works. The URL for the export link should change according to the filters applied, but I think that those same filters make navigation difficult. At this point, I've spent 3.5 hours on this. I am not sure whether this filtering can be resolved in 0.5 hours, but I am going to take a break and proceed a bit later this morning.

````
TypeError: Cannot read property 'Request' of undefined
    at getRecord (/Users/mnyon/code/smoke-alarm-portal/views/admin/requests/index.js:163:26)
    at /Users/mnyon/code/smoke-alarm-portal/node_modules/async/lib/async.js:567:21
    at /Users/mnyon/code/smoke-alarm-portal/node_modules/async/lib/async.js:246:17
    at /Users/mnyon/code/smoke-alarm-portal/node_modules/async/lib/async.js:122:13
    at _each (/Users/mnyon/code/smoke-alarm-portal/node_modules/async/lib/async.js:46:13)
    at async.each (/Users/mnyon/code/smoke-alarm-portal/node_modules/async/lib/async.js:121:9)
    at _asyncMap (/Users/mnyon/code/smoke-alarm-portal/node_modules/async/lib/async.js:245:13)
    at Object.map (/Users/mnyon/code/smoke-alarm-portal/node_modules/async/lib/async.js:216:23)
    at _parallel (/Users/mnyon/code/smoke-alarm-portal/node_modules/async/lib/async.js:565:20)
    at Object.async.parallel (/Users/mnyon/code/smoke-alarm-portal/node_modules/async/lib/async.js:595:9)
    at exports.read (/Users/mnyon/code/smoke-alarm-portal/views/admin/requests/index.js:190:22)
    at Layer.handle [as handle_request] (/Users/mnyon/code/smoke-alarm-portal/node_modules/express/lib/router/layer.js:82:5)
    at next (/Users/mnyon/code/smoke-alarm-portal/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/Users/mnyon/code/smoke-alarm-portal/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/Users/mnyon/code/smoke-alarm-portal/node_modules/express/lib/router/layer.js:82:5)
    at /Users/mnyon/code/smoke-alarm-portal/node_modules/express/lib/router/index.js:267:22
````

**Comment by cecilia-donnelly** [comment]
Reviving this: filtering has still not been added, as of 7f77f58 on master.

**Comment by cecilia-donnelly** [comment]
Note, after conversation with @OhMcGoo and @kfogel yesterday:

The CSV export exists, but doesn't include any filtering yet.  Currently the export will return all entered requests.  I'll look into making it filter correctly.

**Comment by cecilia-donnelly** [comment]
The export is now filtered based on the choices selected by the user and includes the region and serial number.  I'll put this on demo for testing.

**Comment by cecilia-donnelly** [comment]
Deployed as of [2016-01-28].
