### ISSUE TITLE
Region doesn't show in report nor on "thank you" page

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#101]
The region names are not showing up in the `admin/requests` report nor in the text on the "thank you" page for users.  The thank you page shows 

>Thank you for your smoke alarm installation request. Your information has been sent to your local Red Cross. A representative will contact you with information on installation availability in your area. Please allow two to four weeks for a response.

Was removing the region from that page purposeful?

**Comment by cecilia-donnelly** [comment]
I see where the region names disappeared, in commit 12a3ff1.  I just need to change this line from `request.address_2 = recipients_table[selectedRegion]["region_display_name"];` to `request.address_2 = selectedRegion;`

**Comment by kfogel** [comment]
Thanks, @cecilia-donnelly.  (Are these things that were uncovered as part of your testing?  However you ran across them, let's make sure those actions get permanently listed in our testing checklist.)

**Comment by cecilia-donnelly** [comment]
@kfogel agreed.  It turns out that even though I've now successfully made the region appear in the report, the region sorting is not working.  I'll look to see when it was last working and whether I can fix it.

**Comment by cecilia-donnelly** [comment]
Now the region is showing up in the code form, not the display form.

**Comment by cecilia-donnelly** [comment]
Correction: this was showing up correctly in the report, but I hadn't updated my `recipients.json` with the new values.
