### ISSUE TITLE
Date choosers in admin area don't offer clear input UI.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#103]
The "Start Date" and "End Date" filter input fields on `/admin/requests/` don't offer clear UI guidance -- they're just text fields.  The user doesn't know, for example, whether to enter a date in a format like "2015-08-21" or "21-8-15" or "21 Aug 2015" or whatever.  Maybe all of those would work, or maybe none... The user has no way of knowing.  Even after they start typing, the input field gives no clue as to whether they're on the right track or not (see screenshot below).

Date input is pretty much a solved problem, what with date-picker tools and such.  We should just use one of the Usual Solutions here.

![screenshot from 2015-08-21 11-00-21](https://cloud.githubusercontent.com/assets/401111/9412902/47b9df24-47f4-11e5-8bff-0d102937c620.png)

**Comment by nttaylor** [comment]
Closed following d72d70b. Date input now done through jQuery UI datepicker widget.

**Comment by cecilia-donnelly** [comment]
@nttaylor, what was the motivation behind reopening this?  Can it be closed now?

**Comment by cecilia-donnelly** [comment]
@nttaylor, can we close this now?  I believe the datepickers are working correctly and are deployed everywhere.

**Comment by nttaylor** [comment]
I was gunshy about closing issues after I got burned not testing something adequately, but yes I believe these are working and if they also seem to be working to you then we can probably close the issue.
