### ISSUE TITLE
Admin page: Adding name filter causes all other filters & fields to be suddenly filled in too.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#108]
On a fresh /admin/requests page, showing two requests, I entered "Testy" to the name filter field and hit Return (it's also odd that hitting Return is the *only* way to apply a filter, but that's a [separate issue](https://github.com/redcross/smoke-alarm-portal/issues/109)), and suddenly all the other fields were filled in with values too.  They were minimum and maximum values in each case, such that they would have no filtering effect (e.g., a date range from 1980 to 2040, a result count limit of 500, a region filter of "All Regions", etc), but still, it was unexpected that they would go from blank to filled-in just because I happened to enter a name filter and hit Return.

The following three screenshots show the sequence.

First, a blank admin screen showing two requests:

![screenshot from 2015-08-24 21-46-23](https://cloud.githubusercontent.com/assets/401111/9457572/ae640742-4aa9-11e5-8c3c-37a2ccad3b00.png)

Then I enter "Testy" but have not yet hit Return:

![screenshot from 2015-08-24 21-46-29](https://cloud.githubusercontent.com/assets/401111/9457575/b946882e-4aa9-11e5-9ea0-bd7052aac31a.png)

Now here's what happened when I hit Return:

![screenshot from 2015-08-24 21-46-33](https://cloud.githubusercontent.com/assets/401111/9457579/c0c5b0ac-4aa9-11e5-9701-298c2cf5ae7b.png)

**Comment by cecilia-donnelly** [comment]
After admin area updates in several issues (#114, #127, #128, #137...) this is no longer an issue.  Searching in one field no longer fills in the others.
