### ISSUE TITLE
Admin page: no button to apply filters -- user must guess to hit Return.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#109]
As mentioned in passing in issue #108, there's no button to apply filters and/or result page size limit.  The user must guess to hit Return (Enter). Most users probably will guess, and anyway it's for Red Cross admins so they'll be trained, but still, we shouldn't make them guess.  There should be an on-screen control to apply the filters.

Ideally, it would be inactive until the filters are changed from whatever filters are applicable to the current result set, at which point the "Apply" button would become active.  (I'm using "filters" here to mean both filters and the result page size limit, of course.)

**Comment by cecilia-donnelly** [comment]
This is complete, thanks to @nttaylor's work in cc70009 and previous commits.
