### ISSUE TITLE
Server uses arbitrarily chosen earliest and latest dates for filter request

### ISSUE THREAD

**Issue by nttaylor** [redcross/smoke-alarm-portal#114]
Requests from the client for filtered search results can include filters for "start date" and "end date". However, if one or both of these is not chosen by the user as part of the filtering, the server uses the somewhat arbitrary dates of Jan 01, 1980 for the "start date" and Jan 01, 2040 for the "end date".

If the client does not specify a start/end date then the search should be run without any filtering on start/end date at all. Investigation into this issue can begin at `[smokealarm-install-directory]/views/admin/requests/index.js`, which was identified as the source of the behavior by @cecilia-donnelly

**Comment by cecilia-donnelly** [comment]
Deployed as of [2016-01-28].
