### ISSUE TITLE
SMS Requests

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#121]
Users should be able to enter requests for smoke alarms via SMS.  The workflow for this will be as follows:

A. The requester texts some pre-determined/advertised string to a national toll-free number (e.g. 1-800-SMK-ALRM). 

B. The app programmatically responds to the requester with a series of texts instructing them to send (1) their name, (2) their address, (3) their phone number.  These texts will result in the user sending and storing all the same information that he or she would have submitted on the website.  Here is a proposed script for these texts (they will also be translated for Spanish speakers):

> 1: Welcome to the smoke alarm request system (para español, texto "ES").  We need to ask four questions to process your request.  Please text back the answer to each and wait for the next question.  First, what is your name?
2: What is your address, including the unit number, city, state, and zipcode?

(We'll parse the response here and if some of this is missing, text back something like, "Uh-oh, we didn't quite get that.  What is your `<missing piece of information>`?")

> 3: Is the number you're texting from the best way to get in touch with you?  If so, text YES.  Otherwise, please text a phone number where we can reach you.
4: One last question: is there an email address we can use to contact you?  If not, text NONE.  If yes, please text us the email address.
5: Thank you for your smoke alarm request!  Your request number is  `<serial number>`.  To contact your local Red Cross about this request, call `<local phone number>`.  We will be in touch with you to schedule an installation.

C. Once we have all the request data, we send them a confirmation text with their serial number and the phone number of their local Red Cross.

D. The SMS requests will be stored in the same database as the requests submitted through the web site, so Red Cross users who are scheduling installations will be able to see them all through the web site's admin interface.  The database will keep track of whether each request came in through the web site or via SMS.

**Comment by kfogel** [comment]
Pinged @OhMcGoo for comments.

**Comment by OhMcGoo** [comment]
The flow looks good. Am I correct in assuming that getting the "text-to" number is entirely up to us? Two comments: 1. In @cecilia-donnelly's outline, C. would come before 5., I think. 2. It would probably be good to differentiate requests by the portal used as to gain an understanding about how and from where requests are being received.

**Comment by cecilia-donnelly** [comment]
@OhMcGoo, great!  We can choose the text-to number, yes.  I think C. and 5 above are pretty much synonymous, you're right.

We will definitely track whether requests are coming by text or web.  I noted that in D., but I should add explicitly that admin users need to be able to view and sort by that in the admin interface.

**Comment by kfogel** [comment]
I think we left out the part where the appropriate Red Cross admin gets a notification email, just as they currently do with web-based requests, but that of course is also part of this process.  (Though I suspect once things really get going, the people handling the requests will prefer a real dashboard to receiving one-email-per-request, of course.)

**Comment by cecilia-donnelly** [comment]
@nttaylor did some commit review on this (thanks!).  I need to:

- [ ] check to see whether the text we sent was received. (If not, then we'll resend it after some period of time)
- [ ] check whether we're getting the kind of response we expect -- numbers for a phone number, a valid email address where we asked for one, a string for a name.  Right now I just save whatever I get, without any kind of testing.
- [ ] Add an extra as-needed text that specifically asks for their zip code if we couldn't parse it out from their address.
- [ ] Add logic to handle the "ES" option -- right now there's no actual code for sending Spanish texts, and the app would just save their name as "ES"!
- [ ] Save everything we receive.  Right now I'm doing a lot of parsing and guessing, but it's safest to _also_ save the exact strings we receive from the requester.
- [ ] Translate the strings into Spanish and fix the translation of "text 'ES' for Spanish."

Thanks, @nttaylor.  I'm leaving the actual translation to you, but I'll get started on these other improvements.

**Comment by cecilia-donnelly** [comment]
One more!
- [ ] Possibly, also add a "confirmation" text that sends the requester the information we're saving for them and asks if it's correct.  I'm not sure what the right flow would be if they say "No, something is wrong."  @OhMcGoo, do you have any thoughts on that?

**Comment by kfogel** [comment]
On Oct 23, 2015 1:54 AM, "Cecilia Donnelly" <notifications@github.com>
wrote:
>
> @nttaylor did some commit review on this (thanks!). I need to: [...]

That sounds like some in-depth review!  Thanks, @nttaylor.

**Comment by renemarcelo** [comment]
@cecilia-donnelly ,
prefer electrónico vs electronico, in (sms) https://github.com/redcross/smoke-alarm-portal/blob/121-sms-requests/locales/es.js -- everything else looks good.

**Comment by cecilia-donnelly** [comment]
Thanks, @renemarcelo!

The current SMS status is that it works, but is finicky.  Occasionally, these errors come up:

- sometimes can't switch to spanish on first attempt (keeps sending first message multiple times, until it eventually switches)
- sometimes it doesn't send the correct (any) response to the address text, but no error is logged and the request saves correctly if user continues texting (which would of course be impossible for a real user).  I need to do more testing to find out why this happens sometimes and not others.
- once in a while I get a "mash-up" text, where I can tell that a couple different texts have been combined so that I can a nonsensical SMS that is half about "thanks for your request" and half "welcome to the request system."

I suspect that some of this may be because I'm using the "trial" version of Twilio's API.  We'll need to do heavier testing once we sign up for a real account, of course.  We can only send a certain number of texts per minute, for example, and I think that I might be texting too fast for the system, since I'm so familiar with the script.

**Comment by cecilia-donnelly** [comment]
After switching to use the suggested "reply" syntax, this seems to be working more smoothly.  Making this change means that I need to test for failure in a different way, though, which will be my next step.

**Comment by kfogel** [comment]
Set up Twilio billing to go to Red Cross, since RC gets a discount.

**Comment by cecilia-donnelly** [comment]
SMS now works properly when given correct inputs (that is, I don't see the mash-ups and language switching errors that I mentioned in https://github.com/redcross/smoke-alarm-portal/issues/121#issuecomment-153889872).  Things we've mentioned above that still need to be done are:

- [ ]  Save everything we receive in raw form -- not just the parsed version.
- [ ] check whether we're getting the kind of response we expect -- numbers for a phone number, a valid email address where we asked for one, a string for a name.  This will be easier to organize now with our `storeValues()` function.

And, not explicitly mentioned:
- [ ] Test whether our response text was sent and flag as an error if not.  @kfogel, do you think we should save a partial request if one of our responses fails to send?

Note that we also need to set up the "best practices" responses mentioned to us by Twilio.

>You need a toll-free number or support email address where users can contact you for additional information about the program; that contact info must come in response to "HELP" or "INFO" requests via SMS, but other than that it can just be on the web site.

**Comment by kfogel** [comment]
Hmm, maybe I don't understand the question, @cecilia-donnelly.  If one of our responses fails to send, that means we tried to send something to the user but the user didn't get it, right?  That doesn't necessarily mean that we have only a partial request, though -- maybe we have all the information we need, and it's just that we were unable to acknowledge that to the user.  We could still save a full request in that case, right?

I suspect I'm missing something, though; please enlighten as necessary.

**Comment by cecilia-donnelly** [comment]
@kfogel good point.  I was specifically thinking of a case where we have received, say, name and address from the user but our SMS response asking for their phone number failed to send.  In that case we'd have a partial request and would need to save it as part of our error routine.  

I made that comment (https://github.com/redcross/smoke-alarm-portal/issues/121#issuecomment-171383910) a little while ago and am now firmly on the side of "Yes, save partial requests in case of an error."  (Let me know if you disagree!)  I just need to be sure to include code to do that.  Once that's in place we might want to add a filter to the reports page so that admins can see any partial requests, since they (the incomplete requests) wouldn't be automatically assigned to a region.  At least as the code works now, we can't assign to a region without a zipcode.  

There is a minimal case in which we've only received a "start" text -- though even in that case, we have the phone number of the requester.  If the request is incomplete because of an error, then I say we save it.  If, however, the requester stopped halfway through then we wouldn't.

Note: the way this works currently is that as the SMS conversation flows I save each response from the user to a cookie.  Once the request is complete I save the whole request from that cookie to the database.  As I write this, I can see an argument for saving each piece of information to the db as it comes in.  In that case we wouldn't have the "should we save partial requests?" problem, but then the SMS flow would have less in common with the web flow and there might be other complications.  That might be the way to do it, though.

**Comment by cecilia-donnelly** [comment]
@kfogel and I have talked about this, but just so we have it recorded in the issue: to properly test the SMS system we need to set up a real Twilio number (not just the trial version I have) so that we can test with multiple phones at once.  Helping with that testing would also be a good entry point for volunteers.

For now, with the trial Twilio phone number, only my cell phone can text the system and test responses.  That's not ideal for several reasons.  For example, we may find some breakage when multiple people are requesting installations at the same time.

**Comment by kfogel** [comment]
Re data flow: I think saving each piece to the DB as it comes in is best.  The cookie should just serve to identify which row is being updated each time.  Yes, in theory doing this causes more DB transactions, but right now we don't have a problem with that anyway, and it's both an elegant solution to the partial request problem and a generally more standard use of a cookie I think.

**Comment by cecilia-donnelly** [comment]
Work still remaining for the SMS feature:

- [ ] Refactor according to the previous two comments.  Each time a text comes in, save the information to the database.
- [ ] Handle errors correctly.  Check whether texts were sent successfully and send error if not.
- [ ] Code cleanup, perhaps starting with review session.
- [ ] Parallel testing -- does the app handle n people texting at the same time?

**Comment by cecilia-donnelly** [comment]
As @gregbaugues suggested, I'm trying to add delivery receipts so that we can check whether each SMS was delivered.  However, I'm running into the same problem as described in [this StackOverflow question](http://stackoverflow.com/questions/34671345/trouble-with-twilio-twiml-statuscallback-using-node-js).  I'm still looking for more Node docs on this.  It looks very straightforward [in PHP](https://www.twilio.com/docs/api/twiml/sms/message), but my attempt at adding the status check in commit 909ae87 was unsuccessful.

**Comment by OhMcGoo** [comment]
@cecilia-donnelly, @kfogel: I can set-up a call with Twilio (Kevin Krier, Erika Balbuena) on Monday to review this issue.

**Comment by cecilia-donnelly** [comment]
@OhMcGoo perfect, thanks!  I'm going to keep working on it between now and then.

**Comment by cecilia-donnelly** [comment]
I now check the delivery status of each text message after sending it.  Any design thoughts from there, @kfogel?  My instinct would be to resend the text if it failed, but I don't want to cause an infinite loop.  At the moment, I'm checking the delivery status after each text I send.  So, if I resent a text I would then still check the delivery status.  If there was some fundamental problem and the text failed every time, then that behavior would result in an infinite loop, which we clearly don't want.

I imagine that I could count and limit the total number of texts sent to a given number, or something along those lines.

**Comment by cecilia-donnelly** [comment]
Notes from my chat with Kevin Krier:

Since our logs show "delivered" even on those occasions when actual users don't get the text, the `statusCallback` is not going to help us resend texts -- it'll show the exact same information that we see in the logs.

We're unlikely to get "delivered" back when it wasn't actually delivered, though sometimes that happens with Verizon (as has happened to me).  bitly can cause spam-filtering problems (though Twilio has a link shortener if we ever need to send links).  When we can get a specific example of this happening, we should open a support ticket with the SID and Twilio can check it out with the carrier.

**Comment by cecilia-donnelly** [comment]
After Kevin's help, we're now receiving the `POST` requests from Twilio which presumably hold the status of our sent messages.  However, as detailed in #174, our server isn't accepting these `POST` requests.  I need to fix #174 in order to handle errors from Twilio.

However, all of our sent text messages through Twilio show status as "delivered," so even fixing this problem will not necessarily cover all cases where text messages are not truly delivered.

**Comment by cecilia-donnelly** [comment]
Merged and deployed on [2016-04-21].
