### ISSUE TITLE
Alternative background images

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#122]
Let's try out some other options for the background image.  I'm adding some alternative images shortly, and we can test those out on the site.

**Comment by kfogel** [comment]
@cecilia-donnelly @nttaylor Any progress on this?

**Comment by cecilia-donnelly** [comment]
@kfogel not as far as I know, so likely no.  @nttaylor was spending his time largely on #10.  Is that right, Noel?

**Comment by nttaylor** [comment]
Yes that's right, but I will work on this today and tomorrow.

**Comment by kfogel** [comment]
Thanks, @nttaylor!

**Comment by nttaylor** [comment]
One difficulty with the background image has been coming up with an image that looks nice on all screen sizes/shapes.  We can approach this problem from a new direction however by making a collage of images. First up are three backgrounds with different numbers of collage images (ranging from a few large images to many smaller images) as they might appear on a traditional desktop computer.

#1
![screenshot from 2015-11-03 14-19-41](https://cloud.githubusercontent.com/assets/12848962/10920687/258fc1ca-8237-11e5-9309-9872c634a008.png)


#2
![screenshot from 2015-11-03 14-19-51](https://cloud.githubusercontent.com/assets/12848962/10920752/7afa7628-8237-11e5-8238-5d3e67277575.png)

#3
![screenshot from 2015-11-03 14-20-07](https://cloud.githubusercontent.com/assets/12848962/10920761/8872cd5a-8237-11e5-8802-6f7558ae90a8.png)

**Comment by nttaylor** [comment]
And here are the same three backgrounds as they might appear with a narrower aspect ratio (as on a smartphone).

#1
![screenshot from 2015-11-03 14-22-01](https://cloud.githubusercontent.com/assets/12848962/10920870/2617806e-8238-11e5-9373-c1596835de93.png)

#2
![screenshot from 2015-11-03 14-22-16](https://cloud.githubusercontent.com/assets/12848962/10920877/2fb66a72-8238-11e5-898d-494aaef707a8.png)

#3
![screenshot from 2015-11-03 14-22-39](https://cloud.githubusercontent.com/assets/12848962/10920892/3aa7b7b0-8238-11e5-8a7d-46cbdd7cda0c.png)

**Comment by cecilia-donnelly** [comment]
After talking to @nttaylor about this, it sounds like any of these photos could also work by themselves, in place of the current background.  Our current setup has one photo visible on a typical desktop browser, with two visible on a phone (or other smaller) screen.  For mobile compatibility, we're unlikely to ever truly present just one photo.

That is, if none of these collages work, we could choose any of the available photos to be the full desktop-sized background.

**Comment by nttaylor** [comment]
@cecilia-donnelly makes a good point, although naturally some images will make better backgrounds than others. I have selected some that I think work reasonably well as single-image backgrounds and added the screenshots below.  Note that the b&w images used in these screenshots - as well as the collages above - have been added to the 122_alternate-background-images branch (see b55582e and 393cffc).

#1
![screenshot from 2015-11-03 22-46-40](https://cloud.githubusercontent.com/assets/12848962/10929827/097e2778-827e-11e5-98b6-534fcb73d57f.png)

#2
![screenshot from 2015-11-03 22-47-11](https://cloud.githubusercontent.com/assets/12848962/10929830/145592e4-827e-11e5-82d1-2ab68d91ecb8.png)

#3
![screenshot from 2015-11-03 22-47-26](https://cloud.githubusercontent.com/assets/12848962/10929842/2f300662-827e-11e5-9492-a6ddfc536e70.png)

#4
![screenshot from 2015-11-03 22-47-45](https://cloud.githubusercontent.com/assets/12848962/10929850/3b578c8a-827e-11e5-949a-4aaae7095a83.png)

#5
![screenshot from 2015-11-03 22-48-24](https://cloud.githubusercontent.com/assets/12848962/10929855/46207a6e-827e-11e5-92b7-0e02325ef343.png)

**Comment by cecilia-donnelly** [comment]
@OhMcGoo suggests one major image, with smaller images across the bottom of the screen (on a desktop).  On mobile, these images would line up vertically.  Another idea is to show a different image each time the site loads.  In combination, it might be that the smaller images and main image rotate.

In general, @OhMcGoo thinks the collages are too busy.  Let's stick to one image at a time.  Any of the single images would be fine.

**Comment by nttaylor** [comment]
A new concept implemented in ae1e0dc. For wide screens, a four-photo image panel now appears at the bottom of the display showing the installation of a smoke detector. The panel does not appear for narrower screens. See three screenshots taken at different screen widths below. Here is what it looks like on a wide-screen display:

![screenshot from 2015-11-13 14-10-52](https://cloud.githubusercontent.com/assets/12848962/11156553/3c5c2ad2-8a12-11e5-9936-3ceb2cf501c9.png)

Here on a narrower but still desktop-sized display:

![screenshot from 2015-11-13 14-13-07](https://cloud.githubusercontent.com/assets/12848962/11156782/8cd87992-8a13-11e5-9528-74c0c625c23f.png)

And here on a narrow (phone-width) display, where the lower panel does not appear:

![screenshot from 2015-11-13 14-13-48](https://cloud.githubusercontent.com/assets/12848962/11156792/9ca24790-8a13-11e5-97a1-d4dae484df9b.png)

**Comment by kfogel** [comment]
Lovin' it.  Want to know what @OhMcGoo thinks (btw Jim did you get the new username yet?).

**Comment by kfogel** [comment]
From phone call with Jim (@OhMcGoo) today:

Switch primary image to young African-American guy with drill screwdriver.  Then instead of three smaller images along the bottom with black borders, use one image centered with a thin white border (later, this might become an embedded video "See how easy an installation is!" --> click to play).

**Comment by cecilia-donnelly** [comment]
Changes made and deployed to demo.  Check them out and let me know what you think, @kfogel and @OhMcGoo.

![screenshot from 2015-11-23 12-09-13](https://cloud.githubusercontent.com/assets/1497818/11345180/119a2242-91db-11e5-96ac-c28d7998830c.png)

**Comment by cecilia-donnelly** [comment]
Now with darker border.  I've sized the screen so that it's clear how the darker border makes the text more visible:

![screenshot from 2015-11-23 13-57-00](https://cloud.githubusercontent.com/assets/1497818/11348108/36378b76-91ea-11e5-84e2-f6d18a7b245b.png)

**Comment by OhMcGoo** [comment]
I don't like the color photograph; would prefer B&W. Image should bleed to a solid grey on mobile devices rather than tile. Thumbnail should not "underlap" the text, if possible. White border should be thinner. Make sense?

**Comment by cecilia-donnelly** [comment]
@OhMcGoo adds in person: color photo is fine as long as it can bleed smoothly to a solid at the bottom of the image.  Remove the small photo altogether.

**Comment by kfogel** [comment]
The `122_alternate-background-images` was merged to `master` in commit aec63b5e1 and deployed to production.  Further improvements to the background image, and to the appearance of the text over it, are possible, but those can be filed as separate issues.  Closing this one.
