### ISSUE TITLE
Headers of "sorry" and "thank you" are different

### ISSUE THREAD

**Issue by nttaylor** [redcross/smoke-alarm-portal#123]
Here's an easy one that just needs an executive decision: The header text (in `<h1>` tags) of the "sorry" page is "American Red Cross of Chicago & Northern Illinois", but the header text of the "thank you" page is just "American Red Cross".

Which one shall we go with? I'd like to pick one instead of doing (easy but unnecessary) Spanish translations for both.

**Comment by cecilia-donnelly** [comment]
I'd say American Red Cross.  This is being used by many regions, not just CNI.

**Comment by cecilia-donnelly** [comment]
Now the headers both say "American Red Cross," but the sorry page does not have a left margin the same way that the thank you page does.

**Comment by cecilia-donnelly** [comment]
Headers and margins now match.  Deployed by @kfogel.
