### ISSUE TITLE
Text changes

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#126]
Add two links:
1) On the home page, add a link to the "smoke signals" project.
2) On the thank you/sorry page, add a link to the Red Cross preparedness site.

**Comment by OhMcGoo** [comment]
Smoke Signals: http://labs.enigma.io/smoke-signals/ <http://labs.enigma.io/smoke-signals/>

Red Cross: http://www.redcross.org/prepare/location/home-family/prevent-home-fires <http://www.redcross.org/prepare/location/home-family/prevent-home-fires>

**Comment by cecilia-donnelly** [comment]
I added these links, but the text still needs to be translated.  I've kept the change on a branch until we can verify that the text is acceptable and have translated it.

**Comment by cecilia-donnelly** [comment]
Deployed [2015-11-16].  Thanks, @nttaylor!
