### ISSUE TITLE
Region-specific users

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#127]
On the admin side, create a username for each region and automatically filter the displayed requests by that region.

**Comment by cecilia-donnelly** [comment]
I think the design of this will be:

- Add a `user_id` column to the `activeRegions` table.  Each active region will then have an associated `user_id`.  The `user_id` column will be a foreign key to the `Users` table, where the users themselves will be stored (along with their credentials).
- When the admin area loads, it will find the current logged-in user, then find the region corresponding to that user in the `activeRegions` table.  It will then apply a filter based on that region to the results displayed.

What do you think, @kfogel?  Does this look like the right design?  If the current logged-in user is not associated with any specific region then that user will see all regions by default.

Question:
- should all users still be able to filter by region?  That is, even though the default is to only show them requests for their region, should requests for other regions still be visible to them?

**Comment by OhMcGoo** [comment]
We will still need the ability for some Admins to see ALL the records and then be able to filter (or sort) by Region (or other criteria like date).

**Comment by cecilia-donnelly** [comment]
@OhMcGoo definitely.  My question was more about whether, say, the Wisconsin user should be able to see Chicago's requests.

**Comment by cecilia-donnelly** [comment]
Here's a new take on the design after some helpful comments from @kfogel:

We need to have a many-to-many relationship between users and regions.  A given user might have access to one, some, or all regions.  A given region will likely be available to more than one user.

Database:
- Create a new `regionPermission` table with foreign keys to `activeRegions` and `Users`.

UI: 
- When a new user is created, the creator will need to choose which regions the new user has access to.  This implies a new workflow for creating users.  Until now we've used the generic "Sign Up" page, which is currently disabled.  Creating users needs to be an admin functionality.  (This will probably be split out into a separate issue, since I can create the initial regional users in the backend.)
- On the page of requests, the logged-in user should see the "region" filter with all the regions, but the regions that s/he does not have access to will be grayed out.  The region(s) that s/he has access to will be displayed at the top of the list.
- The requests will be filtered to show only those in region(s) that the logged-in user has access to.

**Comment by kfogel** [comment]
Looks good!  The user can, of course, filter further within the set of regions she has access to, to only show a subset of those regions.

**Comment by cecilia-donnelly** [comment]
:+1: Right.  Thanks!

**Comment by cecilia-donnelly** [comment]
This is largely complete and should be easy to merge and deploy (I tested on the demo server and there's no need to manually reload the database).

One question remains: how will this design deal with requests that don't fall into a region?  Naturally a user that has access to all the regions should also be able to view requests that are region-less.

Possible implementation:  We can create a new region code for all the requests that don't fall into any region.  Then we can grant access to that "non-region region" for certain users.

This would involve adding a new entry to the `activeRegions` table, saving all new requests that don't fall into any region with that region code, and updating old requests that don't have a region with that region code.

@kfogel, thoughts?

**Comment by OhMcGoo** [comment]
I agree that we create a "Region" for all requests that don't fall into a North Central Division Region. Then, can you have all those requests e-mailed to me so that they don't get ignored? I do see that we've already received requests from places like California.

**Comment by cecilia-donnelly** [comment]
@OhMcGoo so this is now visible for testing on the demo server.  I granted the "admin" user access to all regions, including the "No Region Found" region (I can change that to whatever name you'd like).  Once this is on the prod server I can set those requests to go to whatever email address you'd like.

**Comment by OhMcGoo** [comment]
Is the Admin password different on the demo site?

**Comment by cecilia-donnelly** [comment]
Deployed as of [2016-01-28].
