### ISSUE TITLE
Add region-specific contact numbers?

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#129]
In our original SMS text (see issue #121), we include a sentence about contacting the local Red Cross region for more information.  I'm removing this for now because we don't have contact phone numbers for each region and I don't want to block SMS on that.  Should we have region-specific phone numbers in the text script?  If so, should we also display them on the website after a user has submitted a request?

**Comment by OhMcGoo** [comment]
Users can call 800-REDCROSS to be connected to their local Region/Chapter. Does that help?

**Comment by cecilia-donnelly** [comment]
@OhMcGoo yes!  I thought we were waiting on more specific phone numbers, but I can just put that generic number in.  Thank you!

**Comment by cecilia-donnelly** [comment]
Merged and deployed on [2016-04-21].
