### ISSUE TITLE
Link text (like "the Smoke Signals project") needs better contrast over background.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#130]
The linked text "the Smoke Signals project" on the front page is now a little bit hard to read over the new background.  Possibly other links need contrast improvement as well (we should check the thank-you page and the sorry page as well as the front page).

**Comment by OhMcGoo** [comment]
Bold and red (but not bright red) is probably best.

**Comment by cecilia-donnelly** [comment]
@OhMcGoo, I added a shaded background here because one color wouldn't look good across the background image.  I also bolded the text.  Happy demo-ing!  Let us know if you want to keep tweaking this.

**Comment by cecilia-donnelly** [comment]
@kfogel and I looked at the links on the thank you and sorry pages and we think they are visible enough.
