### ISSUE TITLE
Fonts look wonky in some browsers (e.g., Debian GNU/Linux Iceweasel or Chromium).

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#131]
For some reason, the Helvetica Neue we're using is looking a bit draggly on Debian GNU/Linux in both Chromium and Firefox (Iceweasel).  I'll attach a screenshot from Iceweasel here; it's the same in Chromium.  This implies it's a system font issue on Debian; we need to do some more cross-browser testing to see where else the site might have this problem -- when we've looked at it in Mac and Windows, it's been fine, but we haven't really done a sizeable browser matrix.

![getasmokealarm-wonky-font-debian-iceweasel-2015-11-30](https://cloud.githubusercontent.com/assets/401111/11490981/37ae327a-97a3-11e5-9f59-4a9500807600.png)

**Comment by kfogel** [comment]
As @OhMcGoo wrote in https://github.com/redcross/smoke-alarm-portal/commit/f952e79d38e367009f0bbddae1381195343040f3#commitcomment-14713945:

> I think the Helvetica Neue Light is TOO light 'across the board.' 

So, let's buckle down and settle the typeface issues once and for all, knowing that we can switch away from Helvetica Neue.  Replacement has to look good in Safari, Chrome, IE, and Firefox (on widely used operating systems).

**Comment by kmattimo** [comment]
I experienced this on windows 8 chrome as well. I noticed in the css there's a rule setting some of the font sizes to .9em. changing it to 1em resolves the weirdness for me. Should test on some of the original machines.

**Comment by cecilia-donnelly** [comment]
Fixed -- thanks @kmattimo!
