### ISSUE TITLE
Move "Smoke Signals" text to bottom, and add open source CFV.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#133]
As I responded in https://github.com/redcross/smoke-alarm-portal/commit/f952e79d38e367009f0bbddae1381195343040f3#commitcomment-14713945:

> I'd like to move the "Smoke Signals" sentence to the bottom, because then it's a natural lead in to the other new sentence we're about to add, which is about how this site's code is open source & we welcome participation etc. Meanwhile, the current closing paragraph obviously should be closely associated with the form fields, so it makes sense for it to come right after them.

**Comment by kfogel** [comment]
Okay, https://demo.getasmokealarm.org/ is showing these changes as of now.  @OhMcGoo, thoughts?  Comments?  Tomatos?

**Comment by OhMcGoo** [comment]
I don’t see the changes on the demo site.

**Comment by cecilia-donnelly** [comment]
@OhMcGoo that's my fault.  I'll put them back now.

**Comment by cecilia-donnelly** [comment]
@OhMcGoo have a look now.

**Comment by OhMcGoo** [comment]
No worries. Trying to get caught up on a week's worth of e-mails so I'm sorry if my replies seem quick and impatient.

**Comment by cecilia-donnelly** [comment]
:+1: No problem!

**Comment by cecilia-donnelly** [comment]
Done and deployed now.
