### ISSUE TITLE
Use https:// for the production server.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#14]
We'll need to get an https:// cert for the production server, to protect people's privacy when their contact details are going over the wire.

**Comment by kfogel** [comment]
Note that INSTALL.md documents this now, as of commit 67f63cae8bce.

**Comment by cecilia-donnelly** [comment]
This is done -- @kfogel and I installed the certs and `getasmokealarm.com` redirects to `https://getasmokealarm.org`.
