### ISSUE TITLE
Please remove the black and white photo from the site; modify main photo to bleed or create a hard break

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#142]
Please remove the black and white photo from the site. Modify main photo to bleed or create a hard break of some kind. The mobile version of the site looks quite unappealing:
![img_2198](https://cloud.githubusercontent.com/assets/4147733/11860429/5c4179dc-a43a-11e5-87e5-406e46fb4618.PNG)

**Comment by kfogel** [comment]
Will do.  I have a vague memory that the way it is now is the result of some non-committal conversation about it, but anyway am too lazy to go trawling through other issues to find out!  I agree it looks weird & should be fixed.  I think a hard break (maybe even with a thin black horizontal border line) followed by a dark background (perhaps with mild texturing, because it can look bad to go from photograph texture to plain color) should do it.  A gray/dark-red similar to the wall color in the photo, maybe?  @cecilia-donnelly, I leave it to your better visual judgement.

**Comment by cecilia-donnelly** [comment]
@OhMcGoo check out a new background on demo now.  I tried to do a textured dark gray/red beneath the main photo.  Let me know how it looks to you -- I've been looking at too many versions of it so my judgment is off.

@kfogel, I took a screenshot if you're interested.  Up close it's more obviously textured than it appears in the photo:

![screenshot from 2015-12-17 11-54-20](https://cloud.githubusercontent.com/assets/1497818/11877446/f1b42a30-a4b4-11e5-87f7-dbacd740eac9.png)

**Comment by OhMcGoo** [comment]
Ideally, I would like the image to fade into a dark red to match the wall, behind.

**Comment by cecilia-donnelly** [comment]
The rest of the background is now a red that matches the wall (see this screenshot or the demo site).  I'll look into fading the pictures together a bit more so there isn't such a hard break.

![screenshot from 2015-12-17 14-20-53](https://cloud.githubusercontent.com/assets/1497818/11880972/8d70da5e-a4c9-11e5-8291-567b5e4c7043.png)

**Comment by kfogel** [comment]
I think this looks acceptable; would like @OhMcGoo's thoughts of course. 

But Jim at some point we should talk about how much investment to make in the aesthetics of the background -- I think it *could* look a lot better, if we really devoted some design time and thought carefully about what kind of photo would be easily adaptable to all screen sizes.  We never really did that: we took some photos that Red Cross happened to have and made it work with those.  I think if we wanted to Do This Right, we'd think from first principles and then stage the kind of photos we need.  (With the current photo, the issue of course is that the guy's shirt becomes column of dark blue that gets cut off in a slightly awkward way by the bottom red field.)

It may well be that this is never high enough priority for it to take precedence over the other things we're doing, and that's fine.  I think the screenshot above is okay, and after all the only thing that really matters is whether the aesthetics would ever distract people from filling in their smoke alarm requests and, you know, saving lives.  But I wanted to point out that there is an option to improve things, and that we could budget it if you want.

**Comment by kfogel** [comment]
Another option:

This would be an easy design contribution for someone to make.  I'll raise it in some forums -- Chi Hack Night but others as well --  and see if we can get some volunteer designers to come up with something better too!

@cecilia-donnelly, assigning this ticket to myself, as that's the next step and it's in my basket, although there may of course be further iterations on the current design.

**Comment by cecilia-donnelly** [comment]
Deployed to prod as of [2016-01-27].  @OhMcGoo let me know if this needs further work.
