### ISSUE TITLE
Form submission succeeds without required fields

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#145]
The front-page form can now be submitted without required fields (indeed, entirely empty) without the "This field is required" tooltips showing up.  However, if the user switches the page language and _then_ attempts to fill out and submit the form, the tooltips and submission work (or block) as expected.

Not sure what's going on here, but I'll look into it.

To be clear, the expected behavior is that the user cannot submit the form without filling in all required fields (all fields, except either phone or email).  Submission fails and tooltips appear over missing fields.  This expected behavior is still what happens if and only if the user has previously changed the language of the page.  If the user has not changed the language (probable in the case where the user prefers the English version) then s/he _can_ submit an incomplete form and no warnings show up.

**Comment by jwm2017** [comment]
It also accepts filled in fields with invalid input. See phone number field in attached image
![phonenumbervalidationissue](https://cloud.githubusercontent.com/assets/10790010/13194778/90502578-d763-11e5-9995-fb6ccc824983.png)

**Comment by mchu0010** [comment]
I'm able to reproduce this bug every time in Firefox 43.0.4 and Safari Version 9.0.3 (10601.4.4) but unable to reproduce this bug reliably in Chrome Version 48.0.2564.116 (64-bit) in Mac OS X Yosemite Version 10.10.5

**Comment by cecilia-donnelly** [comment]
Fixed and deployed -- thanks @mchu0010!
