### ISSUE TITLE
Users can't alter account info

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#149]
On the /account/settings page, users should be able to alter their names and contact information, as well as their usernames and passwords.  After #148, they can alter their passwords, but the other changes on this page are still not available to them.

See https://github.com/redcross/smoke-alarm-portal/commit/37b024c1548279a9f9f3fae1b4d735105c813939 for an example of how to fix this.

**Comment by mchu0010** [comment]
It looks like the users are already able to alter their fist name, middle name, last name, company name, phone, and zip, but not their username and email. I'll try to fix the issue to only allow the users to alter their email because I don't they should be able to change their username.

**Comment by kfogel** [comment]
Oh, I dunno.  Is there any reason we shouldn't let them change their username too, as long as it doesn't collide with some other existing username?

**Comment by OhMcGoo** [comment]
I have no argument against it . . .

**Comment by mchu0010** [comment]
I am still in the middle of testing, and will edit the errors below with more details when I fully understand whats going on. But so far after testing issue #149, I found couple of more errors:
1. The new updated info does not appear until you update it 2-3 times, and the new updated information will always be 2-3 update submissions behind.
2. I logged into 3 different accounts from 3 browsers, and when you update one account, it affects all 3. The new updated information will appear on another account

**Comment by cecilia-donnelly** [comment]
@mchu0010 I just did some testing too.  I have two users, with IDs 1 and 2.  I was logged in as user 1, and already had a name stored with my account ("Cecilia Donnelly").  I logged out and then logged back in as user 2.  The account information that showed up was still Cecilia Donnelly.  I updated it (to "Garrison Keillor," since user 2 is my Minnesota-region-specific user) and the information was updated right away, but the database showed that the updated account was associated with user 1.  That is, even when logged in as user 2, I viewed and updated user 1's information.

Much stranger: I then logged out and logged back in as user 1.  I expected to see "Garrison Keillor," since the database showed that user 1's account had updated to that name.  Instead, the name fields were empty (as they would be if I was logged in as user 2).  When I tried to update the name, that new name saved in the database with the account record associated with user 2.  Very strange!  THEN, suddenly, when I refreshed the page, the Garrison Keillor info showed up again!

So, I believe that the act of updating the record has some relationship to switching the record displayed, but I'm not sure what yet.  The app doesn't seem to have any issue displaying the correct requests for the logged-in user, so I don't think it's a problem with not finding the current user.  Note that this is all in the same browser tab.  I think @mchu0010 was testing in several different browser types and windows, to avoid any possible caching-related weirdness.

What is going on here?  My instinct is that this is another drywall issue like the one fixed in: https://github.com/redcross/smoke-alarm-portal/commit/16c94daa8f03cf118a8b5c01f2abb96850fbac40, but I'm definitely not sure.

**Comment by mchu0010** [comment]
It looks like the problem to the account information not saving to the correct user is because the database call is not finding the correct user. It is missing the "where" inside the database call.
`        req.app.db.Account.findOne({ where:  
                {'UserId': req.user.id}
            })    `
There are many more instances in the code that "where" is missing from the database calls, but there are no error occurring to know if a "where" is needed in those calls.

**Comment by cecilia-donnelly** [comment]
Merged.  Deployed on [2016-04-15].
