### ISSUE TITLE
Change "Sorry' message for SMS requests outside of getasmokealarm.org-using Regions

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#157]
ALL Red Cross Regions install smoke alarms. Not all use getasmokealarm.org. Change the message shown:

![sorry](https://cloud.githubusercontent.com/assets/4147733/13319654/ca244ed6-db88-11e5-9b63-6fe4a45f514b.png)

to read something like **"Sorry, the Red Cross Region serving ______ County, ______ does not yet accept smoke alarm installation requests by text message. Please call 1-800-RED CROSS (1-800-733-2767) to be connected with your local Region."**

I did not get the above screenshot on my iPhone 5S. Instead it came up on an IPhone 6. I'm uncertain what would happen if someone were to hit the **Reply** option.

**Comment by cecilia-donnelly** [comment]
@OhMcGoo updated this on the demo server.  It will be merged to prod with the rest of the SMS (#121) changes, so I'll close this issue.
