### ISSUE TITLE
Add Kansas Counties to the Western Missouri Region

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#163]
Please add the following Kansas Counties to the Western Missouri Region:

Atchison
Doniphan
Johnson
Leavenworth
Wyandotte

**Comment by cecilia-donnelly** [comment]
See [DEVELOPMENT.md](https://github.com/redcross/smoke-alarm-portal/blob/master/DEVELOPMENT.md) for notes on how to do this.

**Comment by mchu0010** [comment]
The 5 Kansas Counties listed above were already in the Western Missouri Region. All the selected counties are located in:

` ./smoke-alarm-portal/data/selected_counties.json `

**Comment by OhMcGoo** [comment]
Thank you, @mchu0010!
