### ISSUE TITLE
Northwest Region Counties

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#164]
**Washington:**
Benton
Chelan
Clallam
Columbia
Douglas
Ferry
Franklin
Grant
Grays Harbor
Island
Jefferson
King
Kitsap
Kittitas
Lewis
Lincoln
Mason
Okanogan
Pend Oreille
Pierce
San Juan
Skagit
Snohomish
Spokane
Stevens
Thurston
Walla Walla
Whatcom
Whitman
Yakima

**Idaho:**
Benewah
Bonner
Boundary
Kootenai
Shoshone

**Comment by cecilia-donnelly** [comment]
@OhMcGoo:
Thanks!  I added these in https://github.com/redcross/smoke-alarm-portal/commit/1c9b35158275e426cb4c7c21ccdc52330a2e3ed0 and they are active now.  See https://github.com/redcross/smoke-alarm-portal/commit/02d875f0c6608ffd803a28999f5887a79f6c7c85 for this list with the updated region abbreviation `NWRN`.  I have all these counties and also Adams County, Washington, in the Northwest Region.

I'll close the issue for now, but feel free to reopen if there's a problem.

**Comment by OhMcGoo** [comment]
Forgot about poor Adams.
