### ISSUE TITLE
Change the "availability" language to reflect added and updated geography

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#167]
The "availability" language on the main page should be updated to:

"This form can accept requests from the following States and Counties: IA (except Harrison, Mills and Pottawattamie Counties), ID, IL, MN, MO, MT, ND, SD, WA (except Clark, Cowlitz, Klickitat, Pacific, Skamania and Wahkiakum Counties), WI and Atchison, Doniphan, Johnson, Leavenworth and Wyandotte Counties in KS, Dakota County, NE and Malheur County, OR. **If your location is not listed, please call 800-RED-CROSS to be connected to your local Red Cross Chapter.**"

**Comment by OhMcGoo** [comment]
@cecilia-donnelly: Seattle has started to use the portal but the availability language hasn't been updated. This is confusing some of their users. Can we bump this up to a high priority?

**Comment by cecilia-donnelly** [comment]
@OhMcGoo thanks for the ping on this!  I've updated the language.

**Comment by OhMcGoo** [comment]
Thanks @cecilia-donnelly! I'll let Seattle know.
