### ISSUE TITLE
POST requests from outside servers fail

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#174]
Any time we try to POST something from curl or Postman or, ahem, the Twilio servers (https://github.com/redcross/smoke-alarm-portal/issues/121#issuecomment-200415876 and onward), we get a 500 response.  

Next steps here:
- where is that 500 coming from?  It looks like we're never even getting into the route handling for each endpoint (e.g. `/sms/response/` or `/login`/), so there's probably a same-origin check somewhere of which we're running afoul.
- [Check out CORS info here.](http://enable-cors.org/server_expressjs.html)
- [It looks like we're setting up the API the right way.](http://bigspaceship.github.io/blog/2014/05/14/how-to-create-a-rest-api-with-node-dot-js/)
- [I hear that NODE_DEBUG can be helpful, but it hasn't shown much yet.](http://www.juliengilli.com/2013/05/26/Using-Node.js-NODE_DEBUG-for-fun-and-profit/)

I know that in #72 we discussed setting the Node server to only listen to localhost, but I don't think that should be related to this problem, since these requests are coming in through the Apache wrapper / proxy server.

**Comment by jtrudell** [comment]
The 500 is coming back with a stacktrace that says "ForbiddenError: invalid csrf token". Looks like it is from csrf and not a CORS issue.

**Comment by cecilia-donnelly** [comment]
Thanks to @ab712 for explaining how to fix this!  See 3151cde for details.
