### ISSUE TITLE
In Admin Reports the End Date search is not inclusive of Date selected

### ISSUE THREAD

**Issue by murraymel** [redcross/smoke-alarm-portal#189]
In Admin Reports, When searching by the End date, the displayed data is not inclusive of the end date selected, only the day(s) before.This does not appear to be an issue with the start date.

**Comment by cecilia-donnelly** [comment]
@starcrunch, @murraymel, it looks like you've fixed this one in 9eab5c5.  Is that right?  Would you mind submitting a pull request?  It'd be great to get this fixed in production.

**Comment by cecilia-donnelly** [comment]
Merged a fix for this in 64b9e02.  I'll note when I deploy.
