### ISSUE TITLE
On 311 site, make Email NOT a required field

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#234]
On https://getasmokealarm.org/311, Email should not be a required field as it is expected that many requestors will not have e-mail addresses.

**Comment by cecilia-donnelly** [comment]
Okay!  Should phone number be a required field?  Currently the rule is that the requester must enter either phone or email.  

To be more verbose, we have a few options: 
1. Leave it as is (one of those fields must be filled in) and assume that the 311 users will always use the phone number and not the email address.
2. Explicitly require phone number _always_, and never require email address.
3. Require neither.

**Comment by OhMcGoo** [comment]
Ah! Then, I tested the site incorrectly. As long as a mandatory phone number doesn't make an e-mail address required, we're good!

**Comment by cecilia-donnelly** [comment]
Well, if you tested and got an unexpected error that's good to know!  What happened?

**Comment by OhMcGoo** [comment]
User error. However, understanding that installers will be trying to fulfill the 311-accepted requests all on one day (September 23), I recommend we make phone number required and e-mail address optional.

**Comment by cecilia-donnelly** [comment]
@pjsier take a look at this thread when you get a chance.  The only 311-specific changes I've made so far are to the appearance of the homepage and the "source" of the request.  Making phone number required, instead of *either* phone number *or* email address would involve editing the rules on the fields.

**Comment by pjsier** [comment]
@cecilia-donnelly just looked through, this would only be on the front end validation, correct?

**Comment by cecilia-donnelly** [comment]
@pjsier yes, that's my understanding.
