### ISSUE TITLE
On "back," submit button remains disabled

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#242]
Hey, @pjsier, I think this is a Firefox bug.  If I submit a request and then click back, the "Submit" button is still disabled, even if I refresh the page:

After first clicking back:
![screenshot from 2017-09-07 11-40-52](https://user-images.githubusercontent.com/1497818/30174714-9f544f9c-93c1-11e7-9c94-582b335c6271.png)

After refresh:
![screenshot from 2017-09-07 11-40-56](https://user-images.githubusercontent.com/1497818/30174716-9f56f918-93c1-11e7-92f0-b6bb30eb932e.png)

**Comment by pjsier** [comment]
I have a fix for this that's working on Firefox, but it's actually a bug on Safari too that the fix isn't working for. It looks like it has to do with jQuery setting an `onunload` event by default: https://stackoverflow.com/a/201406
