### ISSUE TITLE
Translate two primary main page paragraphs fully to Spanish on the Spanish-language page.

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#248]
Currently, the two primary main page paragraphs on the Spanish-language page read as follows:

**The Red Cross and its partners will install a limited number of free smoke alarms for those who cannot afford to purchase smoke alarms or for those who are physically unable to install a smoke alarm. The Red Cross installs a limited number of specialized bedside alarms for individuals who are deaf or hard-of-hearing. To request a free installation, please complete all fields in the form below and click “Submit.”

La Cruz Roja Americana y sus socios han iniciado la Campaña Contra Incendios en el Hogar para reducir las muertes y lesiones causadas por incendios en el hogar en un 25 por ciento durante los próximos cinco años. Depending on where you live and other factors, either an American Red Cross representative or one of our partner organizations will contact you to schedule an installation appointment.**

<img width="1278" alt="smoke alarm - espanol" src="https://user-images.githubusercontent.com/4147733/38594677-154a9fd6-3d0d-11e8-839b-f965d78dd4ea.png">

Both need to be fully translated to Spanish.

**Comment by kfogel** [comment]
Jim will find a Spanish translator, and OTS will coordinate with that translator to update the text.

OTS will update site dev/deploy documentation to note that all front-facing text has to undergo translation when any update happens.

**Comment by kfogel** [comment]
@OhMcGoo do you have a translator you'd like to introduce, or shall I find one?  (Either way is fine.)

**Comment by OhMcGoo** [comment]
I thought I had already uploaded the translated text here last Thursday. Hmmm. The translation, below, was conducted by AML-Global.

La Cruz Roja Americana y sus colaboradores instalarán una cantidad limitada de alarmas de humo gratuitas para aquellos que no tienen la posibilidad económica de comprar alarmas de humo o aquellos que están imposibilitados físicamente para instalar una alarma de humo. La Cruz Roja Americana instala una cantidad limitada de alarmas especializadas junto a la cama para personas sordas o con capacidad auditiva reducida. Para solicitar una instalación gratuita, complete todos los campos en el siguiente formulario y haga clic en "Submit" [Enviar].

La Cruz Roja Americana y sus socios han iniciado la Campaña Contra Incendios en el Hogar para reducir las muertes y lesiones causadas por incendios en el hogar en un 25 por ciento durante los próximos cinco años. Según dónde viva y otros factores, un representante de la Cruz Roja Americana o una de nuestras organizaciones colaboradoras se comunicará con usted para programar una visita de instalación.

**Comment by cecilia-donnelly** [comment]
While working on this, I noticed that the footer also needs translation:

>If you are able to purchase and install your own smoke alarm, but would like information on home fire safety and smoke alarm installation, please visit redcross.org/sound-the-alarm.

>This web site is open source — volunteers welcome at GitHub.

**Comment by OhMcGoo** [comment]
Argh. I’ll get on it.

**Comment by OhMcGoo** [comment]
Footer translation:

“Si puede comprar e instalar su propia alarma de humo pero desea información acerca de seguridad contra incendios en el hogar e instalación de alarmas de humo, por favor visite redcross/sound-the-alarm.”

**Comment by kfogel** [comment]
@cecilia-donnelly Flagging above for you (though I think the issue would have sent you a notification anyway?  Not sure; playing it safe...)

**Comment by cecilia-donnelly** [comment]
I think this can be closed -- is this complete, @OhMcGoo, @kfogel?

**Comment by pjsier** [comment]
Just deployed this to demo and the production site, so it should show up with the correct text now

**Comment by OhMcGoo** [comment]
It appears the site says "cerca a la cama" rather than "cerca de su cama."

**Comment by pjsier** [comment]
@OhMcGoo Sorry for not clarifying that. The previous translation was "junto a la cama" and not "junto de su cama" (guessing that might have been a typo), so I just changed "junto" to "cerca" since it was the difference between them

**Comment by OhMcGoo** [comment]
Let me get clarification.

**Comment by OhMcGoo** [comment]
Per our CEO, the sentence should read: "La Cruz Roja Americana instala una cantidad limitada de alarmas especializadas **cerca de su cama** para personas sordas o con capacidad auditiva reducida."

**Comment by pjsier** [comment]
@OhMcGoo thanks for the clarification! @cecilia-donnelly I'll make another PR for this and I can run the deploy whenever works after it's merged
