### ISSUE TITLE
Requests from Zip Codes 61341, 61350 and 61364 are not being accepted

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#251]
Requestors from Zip Codes 61341 (Marseille, IL), 61350 (Ottawa, IL) and 61364 (Streator, IL) are getting the following message upon submittal:

"Sorry, the Red Cross Region serving La Salle County, Illinois does not utilize this website to accept smoke alarm installation requests. Please call 800-REDCROSS (800-733-2767) to be connected to your servicing Region. Thank you for contacting the Red Cross."

**Comment by kfogel** [comment]
@cecilia-donnelly is taking a look (have assigned the ticket), as per our [chat](https://chat.opentechstrategies.com/#narrow/stream/general/subject/smoke.20alarm/near/30627) in Zulip just now.

**Comment by cecilia-donnelly** [comment]
Merged and deployed on [2018-04-24].

**Comment by OhMcGoo** [comment]
Thanks, @cecilia-donnelly! Having the Disaster Program Specialist in the Chapter confirm that LaSalle County requests are being accepted.

**Comment by cecilia-donnelly** [comment]
Great, thanks @OhMcGoo.
