### ISSUE TITLE
Beginning April 30, all Wisconsin Region smoke alarm requests should be forward to Marytha Blanchard

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#255]
Currently, all Wisconsin Region smoke alarm requests are being sent to Jennifer Laack. Beginning April 30, she will be out of the office for a few weeks and has asked that all requests be forwarded to Marytha Blanchard (marytha.blanchard@redcross.org). In addition, Marytha should be provided her own admin login.

**Comment by kfogel** [comment]
@OhMcGoo, is it okay if the forwarding starts on Friday?  (That way the switchover doesn't have to be the very first thing we do on Monday morning.)

**Comment by OhMcGoo** [comment]
Sure.

**Comment by cecilia-donnelly** [comment]
@OhMcGoo We're now sending requests to Marytha.  She already has an admin account - let me know if she has trouble logging in.
