### ISSUE TITLE
Update 'availability language' on main page

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#282]
New language:
**This form can accept requests from the following states and counties: AR (except Crittenden and Miller Counties), IA, ID, IL, KS, MN, MO, MT, ND, NE, SD, WA (except Clark, Cowlitz, Klickitat, Pacific, Skamania and Wahkiakum Counties), WI and Malheur County, OR. If your location is not listed, please call 800-RED-CROSS to be connected to your local Red Cross Chapter.**

**Comment by frankduncan** [comment]
While I can make an educated guess, I think that the spanish should be updated by someone who speaks the language.  Right now, that text is:

Esta forma puede aceptar solicitudes de los siguientes estados y condados: IA, ID, IL, KS, MN, MO, MT, ND, NE, SD, WA (excepto condados de Clark, Cowlitz, Klickitat, Pacific, Skamania y Wahkiakum), WI y el condado de Malheur, OR.

**Comment by OhMcGoo** [comment]
Esta forma puede aceptar solicitudes de los siguientes estados y condados: AR (excepto condados de Crittenden y Miller), IA, ID, IL, KS, MN, MO, MT, ND, NE, SD, WA (excepto condados de Clark, Cowlitz, Klickitat, Pacific, Skamania y Wahkiakum), WI y el condado de Malheur, OR.

**Comment by frankduncan** [comment]
Fixed by #285
