### ISSUE TITLE
Create a banner at the top of the site announcing in English and Spanish that smoke alarm installations have been suspended

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#293]
The banner should read:

COVID-19 UPDATE: You can request a smoke alarm installation, however, we are temporarily suspending the scheduling of appointments until public health conditions improve.

Esta es una actualización debido a Covid-19: Estamos aceptando solicitudes para la instalación de alarmas de humo. Sin embargo, hemos suspendido las citas hasta que las condiciones de salud pública mejoren.

**Comment by frankduncan** [comment]
This is updated and fixed in production, and on master, so closing.
