### ISSUE TITLE
Change the request confirmation text messages to state in English and Spanish that smoke alarm installations have been suspended

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#294]
The confirmation messages should read:

English:
Thank you for your smoke alarm request! Your request number is (confirmation number). COVID-19 UPDATE: We are temporarily suspending the scheduling of appointments, however, you will be contacted once public health conditions improve.

Spanish:
Gracias por su solicitud para la instalación de una alarma de humo! Su número de solicitud es (confirmation number). Esta es una actualización debido a Covid-19: Hemos suspendido temporalmente las citas. Sin embargo, nos pondremos en contacto con usted una vez las condiciones de salud pública mejoren.

**Comment by frankduncan** [comment]
This is updated and fixed in production, and on master, so closing.
