### ISSUE TITLE
Per-request unique IDs should be meaningful and recognizeable.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#69]
Right now, the unique ID associated with each request is just a sequence number, e.g., 1, 2, 3... 11, 12... etc.

We should probably construct unique IDs that are a little more meaningful, since humans will see them occasionally.  Something like TYPECODE-ZIPCODE-DATE-PADDEDSEQ.  E.g.:

    SAIR-63101-20150912-0001

...where "SAIR" means "Smoke Alarm Installation Request" (thus leaving the door open for other types of service requests in the future, and, for example, for some other type of unique ID to represent the installation event that satisfies the installation request).

I think we *don't* want to put the requester's name anywhere in the ID, because of privacy issues -- the Red Cross may be sending long lists of IDs around, in reports for both internal and external circulation.  Zip Code and date and sequence number don't easily reveal much about identity, which makes the IDs safe for exposure.

**Comment by kfogel** [comment]
As realized when I was writing issue #76:

Once a request is submitted, we should show a real thank-you page that lists the information submitted and tells the person the unique ID of their request, in case they ever communicate with Red Cross out-of-band about it.

**Comment by kfogel** [comment]
Decision w/ client:

We'll use codes like IDMT-20150924-00003, where the last component is a serial number that's unique within the region (not within the day).  The region portion will be designed for readability:

    IDMT
    NDSD
    KSNE
    MINN
    IOWA
    WEMO
    EAMO
    WISC
    CHNI
    CSIL

We'll be switching to those codes as our internal codes too, instead of, e.g., `rc_iowa` etc.

Most of the work has been done on the corresponding issue branch, and even been merged to master, but the above codes have not yet been implemented, and of course there will be database updates on demo and prod servers, and our out-of-band file maintaining the Red Cross recipients list.

**Comment by kfogel** [comment]
Can this be closed now?

**Comment by cecilia-donnelly** [comment]
Yes!  Merged to master and deployed to servers as of 2015-09-16.
