### ISSUE TITLE
Removal of "Sign Up" link in admin area also removes "Contact" link.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#80]
This is described in issue #79; I'm just filing this separate ticket for it as it's technically a separate issue.

**Comment by kfogel** [comment]
Turns out @trystant deliberately removed it, but is restoring it after discussion.

**Comment by cecilia-donnelly** [comment]
The admin area now looks completely different, and has neither a Contact Us nor Sign Up link.  It only has a link to the "requests" report.
