### ISSUE TITLE
When displaying Requests, show unique ID (seq ID), and don't show 'address_2' column.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#81]
At /admin/requests, the details of each request should lose the `address_2` column (we don't use it anymore) and show the per-request unique ID (the seq ID).  The unique ID can be the leftmost column.

I wasn't sure which of the following files (some?  all?)  would need to be changed to do this:

* `views/admin/requests/details.jade`
* `views/admin/requests/index.jade`
* `views/admin/requests/index.js`
* `public/views/admin/requests/details.js`
* `public/views/admin/requests/index.js`

...plus obviously any derived .min.js or .min.js.map files would need to be updated using `grunt` (by the way, if having `grunt` installed globally for command-line use is now a development requirement, we should document that in INSTALL.md; just having it as a local npm installation in package.json wouldn't be enough, right?).

Note this issue is not about removing address_2 in the database schema.  We should do that too, because we're not using it now (it can't even be set from the front page form), but that's a separate issue.  This ticket is just about not displaying that field in requests reports.

**Comment by kfogel** [comment]
Okay to do this as either one or two changes, btw, whichever is easiest.  I filed it as one ticket because the edits seem likely to be pretty closely related.

**Comment by cecilia-donnelly** [comment]
I removed the address_2 column from the view in 0a01b75, but not from the model nor any requests.

**Comment by cecilia-donnelly** [comment]
As of master on commit 08a97a7, the ID shows up in the requests report and address_2 does not.  Note issue #99, which points out that region is currently showing up in a column labeled address_2, but the end user wouldn't know that.
