### ISSUE TITLE
No way to choose "All Regions".

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#91]
On /admin/requests, there needs to be a way to choose "All Regions" (i.e., no Region filter).  I know the region filtering isn't actually hooked up yet, but once it is, this menu needs an All Regions choice.

**Comment by kfogel** [comment]
Handing over to @trystant for review -- Mark, please close if this change looks good to you.

**Comment by cecilia-donnelly** [comment]
As of commit 08a97a7 on master, there is a way to choose "All Regions."
