### ISSUE TITLE
Pre-deployment UI layout & wording tweaks grab bag bonanza festival.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#94]
As per discussion with Jim McGowan on Thursday, 30 July, we need to make the following tweaks (these reference the drawing Jim made, an image of which is attached):

* [x] Put "American Red Cross" logo and name up at top, instead of at bottom.
* [x] Enlarge background photo such that the smoke detector is positioned centered directly beneath the ARC logo and name, and is roughly the same width (or maybe about 80% of the width -- use best judgement).  See candidate new background photos added in subsequent comment in this issue.
* [x] Have the background photo fade out gradually at the bottom of the screen to some neutral gray that fits with the photo.  Of course "bottom of the screen" is not a definite thing, given different screen sizes, but use your standard laptop browser as a rough guide.  The main thing is that the hand installing the smoke detector at the top is clear; if the fadeout happens somewhere between the top of the ladder and the top of the onlooker's head, that's probably about right.  (Well, that refers to the original photo, and we can change to a new photo, as per followup comment in this issue, but you get the idea.)
* [x] We're reverting to the side-wing text panels design for the text areas, albeit with some tweaks.  The "Smoke alarms save lives..." text goes in the left panel.  The "The American Red Cross and its partners..." text goes in the right panel.  The availability language should remain in the bottom panel, still below the Submit button.
* [x] In the State dropdown selector on the front page, use the standard two-letter US Postal Service abbreviations for states rather than their full names (and "DC" for Washington, DC, "PR" for Puerto Rico, etc).
* [ ] Keep layout of the input form fields themselves, but it's okay to squeeze them horizontally to make room for the side text panels (we should have plenty enough room, especially as the only form field that was really at its content-based minimum width was State, and that minimum width is now going to shrink because we're switching to the two-letter abbreviations).
* [x] The availability panel text should change to this, including the bold and underline formatting (well, due to the limitations of Markdown formatting, I can't do a literal underline on the word "your" in the text that follows, so I've indicated it with underscores instead): "This form can accept requests from the following States and Counties: IA, IL, KS, MN, MO, MT, ND, NE, SD, WI, as well as all counties in ID (except Benewah, Bonner, Boundary, Kootenal and Shoshone Counties) and Malheur County, OR, Garfield and Asotin Counties in WA. **If your location is not listed, Please call 800-RECROSS to be connected to \_your\_ local Red Cross Chapter.**"
* [x] The darkened panels behind the text should be somewhat lighter, and should have no borders.
* [x] Use a lighter weight font for all the text, though still use the same Helvetica Neue typeface.
* [x] The Submit button can be bolder, and should have no border, and more rounded corners.

Here's the drawing Jim made when we were discussing all this on Thursday:

![smoke-alarm-ui-tweaks-2015-07-30](https://cloud.githubusercontent.com/assets/401111/9024150/b9518a26-3884-11e5-8789-684dd94c978d.jpg)

**Comment by kfogel** [comment]
Some new images from Jim -- suggest one of the first two, of the installation itself:

![smoke-alarm-installation-close-up](https://cloud.githubusercontent.com/assets/401111/9031330/2f6b6202-3977-11e5-8e40-1cdf20590312.jpg)

![smoke-alarm-installation-close-up](https://cloud.githubusercontent.com/assets/401111/9031332/35e4781c-3977-11e5-84fc-94fa2417a84a.jpg)

![smoke-alarm-installation-at-door](https://cloud.githubusercontent.com/assets/401111/9031334/3d4a0608-3977-11e5-8024-99b1bd0b151c.jpg)

![smoke-alarm-installation-driving-van](https://cloud.githubusercontent.com/assets/401111/9031336/49393740-3977-11e5-9078-e80b3135a7f1.jpg)

![smoke-alarm-installation-posed-by-van](https://cloud.githubusercontent.com/assets/401111/9031340/50145c34-3977-11e5-9189-9b37ae7f7de9.jpg)

![smoke-alarm-installation-walking-ladder](https://cloud.githubusercontent.com/assets/401111/9031342/542d9af6-3977-11e5-8e3d-4a973c2697c9.jpg)

![smoke-alarm-installation-elbow-on-van-window](https://cloud.githubusercontent.com/assets/401111/9031344/5eb82216-3977-11e5-999d-25315e360568.jpg)

**Comment by kfogel** [comment]
Jim agrees the current haunted-house look (as of commit fc99109d) is too spooky.  He sent a PDF design sketch, which I unfortunately can't attach here due to GitHub file-type limitations, but I'll email it to you.  I replied to the PDF with these words: "Well, It looks good in a PDF, where you can control the exact page dimensions, but I think it's hard to make that kind of thing work well on a web site -- too many differently-sized browsers out there, not to mention small-screen mobile devices.  Let me give this to Noel (the fellow you met last Thursday) too so he can get a sense the range of design you're thinking of, and then let him go to town a bit and see what he comes up with."

Please -- go to town!

**Comment by kfogel** [comment]
Ah -- hey, @nttaylor : Turns out Jim had sent the wider-view picture earlier, it was just so similar to the other picture I accidentally added the other one twice!  Here's the wider one:

![smoke-alarm-installation-wider-view](https://cloud.githubusercontent.com/assets/401111/9085710/c8a5251a-3b44-11e5-86e4-ca344e5c9db6.jpg)

**Comment by cecilia-donnelly** [comment]
@nttaylor went to town, as instructed, and I think we now (as of commit 08a97a7 on master) have a layout that satisfies everyone.
